### ISSUE TITLE
config server does not start

### ISSUE THREAD

**Issue by andrew-claassen** [upa/nante-wan#1]
I try to start container manually but it does not start.

t6f@sdwan:~/nante-wan$ sudo /usr/bin/docker run -dt --net=host -v /home/t6f/nante-wan/nante-wan.conf:/etc/nante-wan.conf -v /dev/log:/dev/log -v /home/t6f/nante-wan/html:/var/www/html upaa/nante-wan-config-server
63e1bacb9a55a708e376c75dac4cab6a0994d05972ebb847080040a0da06e65f

This is the log that is shown:
t6f@sdwan:~/nante-wan$ sudo docker logs 63e1bacb9a55a708e376c75dac4cab6a0994d05972ebb847080040a0da06e65f
Traceback (most recent call last):
  File "/root/config-render.py", line 46, in <module>
    of_nginx = open("/etc/nginx/sites-enabled/default")
FileNotFoundError: [Errno 2] No such file or directory: '/etc/nginx/sites-enabled/default'
t6f@sdwan:~/nante-wan$

**Comment by upa** [comment]
Thank you for trying. I forgot to push the latest config-server container image, and I pushed it. please try again after `docker pull upaa/nante-wan-config-server`

**Comment by andrew-claassen** [comment]
Thank you, I build my own but yours now works perfectly.
